###
# Get all students
GET http://localhost:8080/api/students

###
# Get student by ID (Jill)
GET http://localhost:8080/api/students/1

###
# Get student by Name
GET http://localhost:8080/api/students/name/Jill