// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AddCommentData, AddCommentResponses, CreateFundraiserData, CreateFundraiserResponses, CreateUserData, CreateUserResponses, DeleteCommentData, DeleteCommentResponses, DeleteFundraiserData, DeleteFundraiserResponses, DeleteUserData, DeleteUserResponses, GetAllFundraisersData, GetAllFundraisersResponses, GetAllUsersData, GetAllUsersResponses, GetComments1Data, GetComments1Responses, GetCommentsData, GetCommentsResponses, GetFundraiserByIdData, GetFundraiserByIdResponses, GetUserByIdData, GetUserByIdResponses, RegisterUserData, RegisterUserResponses, UpdateFundraiserData, UpdateFundraiserResponses, UpdateUserData, UpdateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>): RequestResult<DeleteUserResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteUserResponses, unknown, ThrowOnError>({ url: '/api/users/{id}', ...options });

export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>): RequestResult<GetUserByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetUserByIdResponses, unknown, ThrowOnError>({ url: '/api/users/{id}', ...options });

export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>): RequestResult<UpdateUserResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateUserResponses, unknown, ThrowOnError>({
    url: '/api/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteFundraiser = <ThrowOnError extends boolean = false>(options: Options<DeleteFundraiserData, ThrowOnError>): RequestResult<DeleteFundraiserResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteFundraiserResponses, unknown, ThrowOnError>({ url: '/api/fundraisers/{id}', ...options });

export const getFundraiserById = <ThrowOnError extends boolean = false>(options: Options<GetFundraiserByIdData, ThrowOnError>): RequestResult<GetFundraiserByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetFundraiserByIdResponses, unknown, ThrowOnError>({ url: '/api/fundraisers/{id}', ...options });

export const updateFundraiser = <ThrowOnError extends boolean = false>(options: Options<UpdateFundraiserData, ThrowOnError>): RequestResult<UpdateFundraiserResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateFundraiserResponses, unknown, ThrowOnError>({
    url: '/api/fundraisers/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllUsers = <ThrowOnError extends boolean = false>(options?: Options<GetAllUsersData, ThrowOnError>): RequestResult<GetAllUsersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllUsersResponses, unknown, ThrowOnError>({ url: '/api/users', ...options });

export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>): RequestResult<CreateUserResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateUserResponses, unknown, ThrowOnError>({
    url: '/api/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const registerUser = <ThrowOnError extends boolean = false>(options: Options<RegisterUserData, ThrowOnError>): RequestResult<RegisterUserResponses, unknown, ThrowOnError> => (options.client ?? client).post<RegisterUserResponses, unknown, ThrowOnError>({
    url: '/api/users/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllFundraisers = <ThrowOnError extends boolean = false>(options?: Options<GetAllFundraisersData, ThrowOnError>): RequestResult<GetAllFundraisersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAllFundraisersResponses, unknown, ThrowOnError>({ url: '/api/fundraisers', ...options });

export const createFundraiser = <ThrowOnError extends boolean = false>(options: Options<CreateFundraiserData, ThrowOnError>): RequestResult<CreateFundraiserResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateFundraiserResponses, unknown, ThrowOnError>({
    url: '/api/fundraisers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getComments = <ThrowOnError extends boolean = false>(options: Options<GetCommentsData, ThrowOnError>): RequestResult<GetCommentsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetCommentsResponses, unknown, ThrowOnError>({ url: '/api/fundraisers/{fundraiserId}/comments', ...options });

export const addComment = <ThrowOnError extends boolean = false>(options: Options<AddCommentData, ThrowOnError>): RequestResult<AddCommentResponses, unknown, ThrowOnError> => (options.client ?? client).post<AddCommentResponses, unknown, ThrowOnError>({
    url: '/api/fundraisers/{fundraiserId}/comments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getComments1 = <ThrowOnError extends boolean = false>(options: Options<GetComments1Data, ThrowOnError>): RequestResult<GetComments1Responses, unknown, ThrowOnError> => (options.client ?? client).get<GetComments1Responses, unknown, ThrowOnError>({ url: '/api/fundraisers/{id}/comments', ...options });

export const deleteComment = <ThrowOnError extends boolean = false>(options: Options<DeleteCommentData, ThrowOnError>): RequestResult<DeleteCommentResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteCommentResponses, unknown, ThrowOnError>({ url: '/api/fundraisers/{fundraiserId}/comments/{commentId}', ...options });
