// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type User = {
    id?: string;
    username: string;
    password: string;
};

export type Comment = {
    id?: string;
    text: string;
    authorUsername: string;
    fundraiserId?: string;
    postedAt?: string;
    timeAgo?: string;
};

export type Fundraiser = {
    id?: string;
    title?: string;
    description?: string;
    owner: User;
    startDate?: string;
    endDate?: string;
    targetAmount?: number;
    currentAmount?: number;
    comments?: Array<Comment>;
};

export type DeleteUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type DeleteUserResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUserByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type GetUserByIdResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserData = {
    body: User;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type DeleteFundraiserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/fundraisers/{id}';
};

export type DeleteFundraiserResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetFundraiserByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/fundraisers/{id}';
};

export type GetFundraiserByIdResponses = {
    /**
     * OK
     */
    200: Fundraiser;
};

export type GetFundraiserByIdResponse = GetFundraiserByIdResponses[keyof GetFundraiserByIdResponses];

export type UpdateFundraiserData = {
    body: Fundraiser;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/fundraisers/{id}';
};

export type UpdateFundraiserResponses = {
    /**
     * OK
     */
    200: Fundraiser;
};

export type UpdateFundraiserResponse = UpdateFundraiserResponses[keyof UpdateFundraiserResponses];

export type GetAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type GetAllUsersResponses = {
    /**
     * OK
     */
    200: Array<User>;
};

export type GetAllUsersResponse = GetAllUsersResponses[keyof GetAllUsersResponses];

export type CreateUserData = {
    body: User;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type RegisterUserData = {
    body: User;
    path?: never;
    query?: never;
    url: '/api/users/register';
};

export type RegisterUserResponses = {
    /**
     * OK
     */
    200: User;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type GetAllFundraisersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/fundraisers';
};

export type GetAllFundraisersResponses = {
    /**
     * OK
     */
    200: Array<Fundraiser>;
};

export type GetAllFundraisersResponse = GetAllFundraisersResponses[keyof GetAllFundraisersResponses];

export type CreateFundraiserData = {
    body: Fundraiser;
    path?: never;
    query?: never;
    url: '/api/fundraisers';
};

export type CreateFundraiserResponses = {
    /**
     * OK
     */
    200: Fundraiser;
};

export type CreateFundraiserResponse = CreateFundraiserResponses[keyof CreateFundraiserResponses];

export type GetCommentsData = {
    body?: never;
    path: {
        fundraiserId: string;
    };
    query?: never;
    url: '/api/fundraisers/{fundraiserId}/comments';
};

export type GetCommentsResponses = {
    /**
     * OK
     */
    200: Array<Comment>;
};

export type GetCommentsResponse = GetCommentsResponses[keyof GetCommentsResponses];

export type AddCommentData = {
    body: Comment;
    path: {
        fundraiserId: string;
    };
    query?: never;
    url: '/api/fundraisers/{fundraiserId}/comments';
};

export type AddCommentResponses = {
    /**
     * OK
     */
    200: Comment;
};

export type AddCommentResponse = AddCommentResponses[keyof AddCommentResponses];

export type GetComments1Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/fundraisers/{id}/comments';
};

export type GetComments1Responses = {
    /**
     * OK
     */
    200: Array<Comment>;
};

export type GetComments1Response = GetComments1Responses[keyof GetComments1Responses];

export type DeleteCommentData = {
    body?: never;
    path: {
        fundraiserId: string;
        commentId: string;
    };
    query?: never;
    url: '/api/fundraisers/{fundraiserId}/comments/{commentId}';
};

export type DeleteCommentResponses = {
    /**
     * OK
     */
    200: unknown;
};
